# Generated by Django 5.2 on 2026-02-26 20:45

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Название слайдера для отображения в админке",
                        max_length=200,
                        verbose_name="Название",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Уникальный идентификатор для URL (например: main-gallery)",
                        max_length=200,
                        unique=True,
                        verbose_name="URL-адрес",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Показывать ли слайдер на сайте",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
            ],
            options={
                "verbose_name": "Слайдер",
                "verbose_name_plural": "Слайдеры",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SliderItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, editable=False, verbose_name="Порядок"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Название изображения для отображения в админке",
                        max_length=200,
                        verbose_name="Название",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Показывать ли элемент в слайдере",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "image",
                    filer.fields.image.FilerImageField(
                        help_text="Изображение для слайдера",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slider_items",
                        to=settings.FILER_IMAGE_MODEL,
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "slider",
                    models.ForeignKey(
                        help_text="Слайдер, к которому относится этот элемент",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="gallery.slider",
                        verbose_name="Слайдер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент слайдера",
                "verbose_name_plural": "Элементы слайдера",
                "ordering": ["order"],
            },
        ),
    ]
