# Generated by Django 5.2 on 2026-02-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slideritem",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name="Порядок"),
        ),
    ]
